import json
import logging
from langchain_groq import ChatGroq
from langchain_core.messages import SystemMessage, HumanMessage

logger = logging.getLogger(__name__)

SYSTEM = """You are a professional technology analyst writing an executive report.
Write in clear, structured Markdown. Use concrete, specific language.
Do NOT invent company names, statistics, or URLs that are not in the material given to you."""

HUMAN = """Write a structured executive report using the analysis and verified sources below.

=== VERIFIED SOURCES ===
Use ONLY these URLs when citing sources. Each source has an index number, title, and URL.
When you cite a source inline, use the format: ([Title](URL))
In the References section, list each source as: - [Title](URL)
Do NOT use bare index numbers like [1] or [10] — always write the full markdown link.

{source_list}

=== ANALYSIS (JSON) ===
{analysis}

=== CRITIC FEEDBACK ===
{critique}

Report structure — use these exact Markdown headings and fill in every section:

# GenAI in FMCG Supply Chains: Top 5 Emerging Use Cases

## Executive Summary
Write 3-4 sentences covering: what this report examines, which 5 use cases were identified,
and the overall maturity of GenAI adoption in FMCG supply chains.

## Use Case 1: [copy name from analysis]
### GenAI Technology
[exact GenAI technology from analysis — must name a specific model or architecture]
### Supply Chain Area
[specific area]
### Implementation Approach
[Write 3-4 full sentences explaining: which foundation model is used, what data it processes,
how it integrates with existing systems like ERP/WMS/TMS, and what the output looks like.
Do not write a one-liner. Do not repeat the use case name as the implementation.]
### Expected Impact
[specific outcome — include mechanism, cite a source URL if one supports it]
### Key Risks
[2-3 GenAI-specific risks, one sentence each]
### Maturity: [level from analysis]
### Real-World Examples
[Company names with outcomes, or "Evidence pending" — never write a vendor name as a company example]

(Repeat the above block for Use Cases 2 through 5)

## Cross-Cutting Observations
Write 2-3 paragraphs covering patterns across use cases: which GenAI technologies appear
most frequently, which supply chain areas are most mature, and what infrastructure
dependencies (cloud providers, ERP systems) are common.

## Limitations and Caveats
Be honest: note where evidence is thin, which use cases lack named company examples,
and what the limitations of Llama-3.1-8B as the research model are.

## References
List ONLY URLs that appear in the VERIFIED SOURCES section above.
Format every reference as: - [Title](URL)
Do not use bare numbers. Do not invent URLs."""


def _build_source_list(sources: list) -> str:
    if not sources:
        return "No external sources were retrieved."
    lines = []
    for i, s in enumerate(sources, 1):
        lines.append(f"[{i}] Title: {s['title']}\n    URL: {s['url']}")
    return "\n".join(lines)


def report_agent(state: dict) -> dict:
    llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)
    logger.info("[REPORTER] Generating final report...")

    sources = state.get("sources", [])
    analysis = state.get("analysis", "No analysis available.")
    critique = state.get("critique", "No critique available.")
    score = state.get("critique_score", "N/A")

    source_list = _build_source_list(sources)

    # Pretty-print JSON analysis if possible
    try:
        parsed = json.loads(analysis)
        analysis_str = json.dumps(parsed, indent=2)
    except (json.JSONDecodeError, TypeError):
        analysis_str = analysis

    response = llm.generate([[
        SystemMessage(content=SYSTEM),
        HumanMessage(content=HUMAN.format(
            source_list=source_list,
            analysis=analysis_str[:6000],
            critique=critique,
        )),
    ]])
    final_report = response.generations[0][0].message.content

    # Append metadata footer
    final_report += (
        f"\n\n---\n*Report generated by multi-agent pipeline. "
        f"Critic score: {score}/10. "
        f"Revision cycles: {state.get('revision_count', 0)}. "
        f"Sources retrieved: {len(sources)}.*"
    )

    state["final_report"] = final_report
    logger.info("[REPORTER] Report complete (%d chars).", len(final_report))
    return state

    sources = state.get("sources", [])
    analysis = state.get("analysis", "No analysis available.")
    critique = state.get("critique", "No critique available.")
    score = state.get("critique_score", "N/A")

    source_list = _build_source_list(sources)

    # Pretty-print JSON analysis if possible
    try:
        parsed = json.loads(analysis)
        analysis_str = json.dumps(parsed, indent=2)
    except (json.JSONDecodeError, TypeError):
        analysis_str = analysis

    response = llm.generate([[
        SystemMessage(content=SYSTEM),
        HumanMessage(content=HUMAN.format(
            source_list=source_list,
            analysis=analysis_str[:6000],    # token guard
            critique=critique,
        )),
    ]])
    final_report = response.generations[0][0].message.content

    # Append metadata footer
    final_report += (
        f"\n\n---\n*Report generated by multi-agent pipeline. "
        f"Critic score: {score}/10. "
        f"Revision cycles: {state.get('revision_count', 0)}. "
        f"Sources retrieved: {len(sources)}.*"
    )

    state["final_report"] = final_report
    logger.info("[REPORTER] Report complete (%d chars).", len(final_report))
    return state
